### ISSUE TITLE
No MQTT Last Will and Testament

### ISSUE THREAD

**Issue by mkfink** [OpenEVSE/ESP8266_WiFi_v2.x#113]
No MQTT last will and testament is set so it is not obvious if the charge station drops offline (without some other program watching for the regular 30-second telemetry)

**Comment by glynhudson** [comment]
Done :+1: 

Good idea. Would it be possible for you to confirm? Please test latest master branch. Openevse should post `disconnected` to the openevse base topic if the unit drops offline.

**Comment by glynhudson** [comment]
I'm assuming this is fixed. It's working for me.

**Comment by mkfink** [comment]
Just had a chance to test it. Confirmed working here as well, thanks!
