### ISSUE TITLE
Hardware reset

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP8266_WiFi_v2.x#137]
Add the ability to clear all EEPROM settings by holding down a button (GPIO0 / boot) at startup to wipe all EEPROM settings and factory reset the device. Would be a fail safe for #118 or if the http authentication password has been forgotten. 

A number of users are managing to lock themselves out of the device.

**Comment by CliffStoll** [comment]
Yes please!   The inability to reset the wifi password has wasted several hours.  And it's silly to have to reprogram the system just to clear the wifi password.  Imagine if your cellphone worked that way...

**Comment by chris1howell** [comment]
This was part of 1.x...

It would make more sense to go into AP mode with a long press of the
external button via RAPI. And use the Reset/hardware button for factory
reset.

while (buttonState == LOW) {
  buttonState = digitalRead(0);
  erase++;
  if (erase >= 5000) {
    ResetEEPROM();
    int erase = 0;
    WiFi.disconnect();
    Serial.print("Finished...");
    delay(2000);
    ESP.reset();
  }
}

**Comment by chris1howell** [comment]
I have reprogrammed several boards this week due to forgotten passwords. Users are frustrated with the process to erase/reprogram.

**Comment by glynhudson** [comment]
Noted, we'll get onto this. sorry for the hassle.

**Comment by glynhudson** [comment]
Done, implemented in https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/pull/180
