### ISSUE TITLE
Once enabled, emoncms & mqtt cannot be disabled

### ISSUE THREAD

**Issue by sandeen** [OpenEVSE/ESP8266_WiFi_v2.x#14]
The javascript under the save-emoncms element checks for null server name and wrong-length API key, and fails the save request in those cases.  However, this makes it impossible to gracefully disable the emoncms push once it has been configured.  (Similar problems exist for mqtt)
Either an "enable" checkbox, or simply adding the ability to save empty server name + empty API key, would allow the service to be turned off if desired.

**Comment by glynhudson** [comment]
Functionality added in #40 :+1:
