### ISSUE TITLE
Date sync bug still occurs in firmware v2.6.0 but not as badly

### ISSUE THREAD

**Issue by ForumLeech** [OpenEVSE/ESP8266_WiFi_v2.x#156]
Date continues to sync incorrectly when using wifi firmware v2.6.0 but it's not as bad as previous firmware. It consistently syncs to tomorrow. Problem persists after doing a restart on both modules. Occurs in latest version of IE, Chrome, and Firefox on a Windows PC and in latest iOS Safari web browser. 

![capture](https://user-images.githubusercontent.com/2907356/36574303-f9229f44-17f9-11e8-82fc-5512f554ca29.PNG)
![capture3](https://user-images.githubusercontent.com/2907356/36574854-7a46247c-17fc-11e8-8f7b-da5be7f9a891.PNG)
![capture2](https://user-images.githubusercontent.com/2907356/36574367-55c67a86-17fa-11e8-8e49-1f723ec7a0ae.PNG)

**Comment by glynhudson** [comment]
Thanks for reporting. We will take a look. For reference the original issue: https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/issues/119 which should have been fixed by https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/pull/132 by @joverbee.

Can you replicate this issues @joverbee ?

**Comment by glynhudson** [comment]
Sorry, but I'm unable to replicate. Could you try the latest version V2.7.0 and confirm if this is still an issue: https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/releases/tag/2.7.0

I'm using Chrome 64.0.3282.190 64bit. Also tested on Firefox and Android.

**Comment by ForumLeech** [comment]
Yes the date and time sync are working perfectly now after upgrading to
v2.7.0. Thanks for notifying me!
