### ISSUE TITLE
Add nice iOS icon

### ISSUE THREAD

**Issue by sandeen** [OpenEVSE/ESP8266_WiFi_v2.x#160]
I recently added the link to my OpenEVSE to my iphone home screen.  It'd be really nice to have a pretty icon for this.  :)

Apparently a handful of sizes is ideal, for various devices, for example (likely not the recommended sizes):

```
<link rel="apple-touch-icon" sizes="57x57" href="apple-icon-57x57.png" />
<link rel="apple-touch-icon" sizes="72x72" href="apple-icon-72x72.png" />
<link rel="apple-touch-icon" sizes="114x114" href="apple-icon-114x114.png" />
<link rel="apple-touch-icon" sizes="144x144" href="apple-icon-144x144.png" />
```

but if there's not room for that many, just adding:

`<link rel="apple-touch-icon" sizes="32x32" href="/favicon-32x32.png" />`

to use the existing favicon might be nice.

[Configuring Web Applications for iOS](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html)

[Currently preferred icon sizes](https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/)

If there's a higher resolution source for the current favicon I'll play with this if people think it's a good idea.
Thanks,
-Eric

**Comment by glynhudson** [comment]
Sounds great. Any change of a pull request to ensure your exact working code is merged? I don't have an ios device to test on

**Comment by sandeen** [comment]
I haven't done it yet but if you're game I will.  Is there a hi-res version of the logo somewhere?  Are there concerns about spiffs space restraints?  (actually I've lost the thread on where the html content is even stored these days ...)

**Comment by glynhudson** [comment]
the html files are stored in `html/` then the minified js versions are generated on platform io compile and stored in `/data`. Any changes should be made to `html/`.

Yes, resources on the ESP are an issue. How large will the hi-res logo be? What is the pixel dimensions? 

@chris1howell do you have a copy of the openevse logo in high-res?

**Comment by Suriv** [comment]
https://realfavicongenerator.net/

Twitter image:
![pngicon_400x400](https://user-images.githubusercontent.com/286886/50863507-28fe6800-139f-11e9-905f-5dbf38667348.png)

Configuration:
Favicon for iOS - Web Clip
![captura de pantalla 2019-01-08 a las 23 44 48](https://user-images.githubusercontent.com/286886/50863592-6fec5d80-139f-11e9-979e-dd5e8749b715.png)

Favicon for Android Chrome
![captura de pantalla 2019-01-08 a las 23 47 37](https://user-images.githubusercontent.com/286886/50863695-ce194080-139f-11e9-98e8-4c235a6943e3.png)

Windows 10
![captura de pantalla 2019-01-08 a las 23 48 17](https://user-images.githubusercontent.com/286886/50863732-ef7a2c80-139f-11e9-9b3d-46c7cee54ce8.png)

macOS Safari
![captura de pantalla 2019-01-08 a las 23 48 53](https://user-images.githubusercontent.com/286886/50863759-01f46600-13a0-11e9-986d-0a20b4fbb03d.png)

HTml5
<link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
<link rel="manifest" href="site.webmanifest">
<link rel="mask-icon" href="safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">

packed
[favicon_package_v0.16.zip](https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/files/2738690/favicon_package_v0.16.zip)
