### ISSUE TITLE
Simulator error 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP8266_WiFi_v2.x#165]
I've just updated the simulator on our sever to the latest version. It seems to throws a js error:

`Uncaught ReferenceError: Unable to process binding "text: function (){return itemsLoaded }"
Message: itemsLoaded is not defined` 

https://openevse.openenergymonitor.org/

![selection_209](https://user-images.githubusercontent.com/758844/37106951-f9ea98b0-222a-11e8-8a5c-6c16f95e78b6.png)

Interestingly when I run the simulator locally it runs fine. The error must either be due to serving via apache or https. Have you got any ideas?

**Comment by jeremypoulter** [comment]
Sounds like the HTML resources are out of date.

**Comment by jeremypoulter** [comment]
Actually, is working fine for me...

**Comment by glynhudson** [comment]
Ah, also seems to be working fine for me now! Could have been a cloudflare for browser cache issue.
