### ISSUE TITLE
Delay timer field too small when

### ISSUE THREAD

**Issue by moeabm** [OpenEVSE/ESP8266_WiFi_v2.x#168]
Start/Stop Timer fields cut off the AM/PM text con chrome due to 12-hour clock control. Can we make these a bit wider to accommodate chrome's up/down controls?  Firefox shows 24-hour clock so its a non-issue.

**Comment by moeabm** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

**Comment by glynhudson** [comment]
Sure, I guess it would not be a difficult change. However when I test with Chrome and Android they both show 24hr clock so AM/PM not an issue. My preferance would be to always use 24hrs clock  

![screenshot 2018-03-25 at 02 47 09](https://user-images.githubusercontent.com/758844/37870824-f4cbf0b8-2fd6-11e8-9376-1aa4310f9584.png)

**Comment by moeabm** [comment]
I also prefer 24-hour clock but it seems to be browser defined.
