### ISSUE TITLE
How to connect to OpenEVSE Wifi without access to the local network and without Emoncms?

### ISSUE THREAD

**Issue by DeltaVetal26** [OpenEVSE/ESP8266_WiFi_v2.x#185]
Hi! Is it possible to access OpenEVSE Wifi if I'm not at home for example and I do not have Emoncms? At home I connect to the local address: http://192.168.1.123 When I'm not at home, I do not understand how to access the charging control.

**Comment by jeremypoulter** [comment]
Not natively, however if your router supports setting up a VPN this can be used to connect to your home network from anywhere. Alternatively you could use port mapping on the router to open up a direct connection to the OpenEVSE WiFi, however I wouldn't recommend this, and if you do make sure the OpenEVSE WiFi authentication is enabled.
