### ISSUE TITLE
Setting  defaults

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP8266_WiFi_v2.x#19]
I realised when merging the recent changes to EmonESP that I had inadvertently removed all the default values from the HTML UI and I was considering adding them back when it occurred to me that maybe the best solution is that the defaults should probably only be set in the ESP code (ie config.c) as that is really the only place that can tell an empty string from an unset value, (ok maybe not the only place, but certainly the easiest).

Anyone have an issue with putting the defaults in config.c and leaving the HTML as just a pass through?

**Comment by glynhudson** [comment]
Ah yes, good idea. Yup, I'm happy with that. That's a better solution.
