### ISSUE TITLE
Firmware and Protocol Versions 

### ISSUE THREAD

**Issue by chris1howell** [OpenEVSE/ESP8266_WiFi_v2.x#212]
Reported to support by Richard House

Versions:
Advanced kit purchased Dec 2018
OpenEVSE Firmware 5.01
Wifi firmware 2.7.7
Same behaviour confirmed with 4.8.0 and 2.7.5

Symptoms:
When switching on from a cold start, the web interface home page with Advanced Display enabled does not display the correct Firmware and Protocol versions. Numbers for Firmware are either 6 or 12 and Protocol is 0200. See attached screen shot.

Steps to reproduce:
1. Switch power supply off
2. Switch power supply on
3. Naviagate in browser to device home page.
4. Enable advanced display.

Comments:
Using the RAPI commands returns the correct version numbers.
This issue can be corrected by clicking the OpenEVSE Wifi restart button in the web interface.

Suspect that on a cold start, when the Wifi web interface polls the OpenEVSE controller, the OpenEVSE is not fully active.

**Comment by jeremypoulter** [comment]
Will take a look, did add some code to handle that case but have not checked it is working in a while.
