### ISSUE TITLE
RFE: Configurable hostname

### ISSUE THREAD

**Issue by sandeen** [OpenEVSE/ESP8266_WiFi_v2.x#217]
I'm on the verge of possibly having 2 openevse units in the garage.  It'd be really nice to be able to set the hostname(s) so they don't clash in MDNS, for example.  Bonus points for automatically setting the mqtt base topic to match.

I can try to look at this, but I've really kind of lost the thread on how the UI interfaces with the code these days.  :)

**Comment by jeremypoulter** [comment]
Going to take a look at this as I have several dev boards as well as an actual OpenEVSE now ;-)
