### ISSUE TITLE
How can I get the current from EVSE using RAPI and a separate ESP?

### ISSUE THREAD

**Issue by DeltaVetal26** [OpenEVSE/ESP8266_WiFi_v2.x#220]
Hi,

I have a separate ESP32, with which I want to find out the current current and send it to the WebSocket server. The problem is that I can't figure out how to recognize the answer to the $ GE or $ GC commands. All query commands have an answer in a similar style: "$ OK arg1 arg2". Everywhere there is $ OK, but there is no identifying mark, with the help of which I could understand which command the answer came from EVSE.

I thought about it and I got the idea to implement the recognition of commands on the principle of "fishing net".

Example:
I want to get the current settings, for this I send the EVSE command $ GC. Immediately after sending, I launch the "fishing net", which catches the reverse message with the "$ OK" tag, if the answer comes within 5 seconds after sending $ GE, I consider it to be the current settings received.

Will this be the right decision?

**Comment by jeremypoulter** [comment]
Hi, yes you have to assume that the next `$OK` you receive is related to the command you just sent, see https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/blob/master/src/RapiSender.cpp
