### ISSUE TITLE
New UI Memory Usage 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP8266_WiFi_v2.x#226]
This issue is to track / record the increase in data / program memory required 

Old: https://github.com/OpenEVSE/openevse_wifi_gui/commit/7036fe9cc9fe5504270ee6a870061fb5047a7a8a
New: https://github.com/Suriv/openevse_wifi_gui/commit/207d4ec3425511219ffa816954ff559a294f9779

Compiled .bin size 690.6kB > 782.2kB

![Selection_176](https://user-images.githubusercontent.com/758844/57546214-31b67900-7354-11e9-837e-5ad2f84b4025.jpg)

**Comment by jeremypoulter** [comment]
So ~100kB increase, that is probably acceptable.

**Comment by glynhudson** [comment]
Seems to be working fine on the ESP8266, been running it on my home OpenEVSE over the weekend, loading time is a bit slower though, but just about acceptable. See video (loading graphic still need some work) https://drive.google.com/file/d/1cYGzEHU0iaeAwBxsqUun7kfyDvDXbsD0/view

**Comment by Pukkahq** [comment]
@glynhudson 

That looks a little slow, I access the web page on a regularly on my mobile device to turn on eco charging and then to stop charging one we are producing < 6A. can these be settable default options.

**Comment by glynhudson** [comment]
I agree, this new UI is in early stage development. We will ensure performance is higher before release.
