### ISSUE TITLE
Solar PV divert calculates incorrect charging rate 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP8266_WiFi_v2.x#227]
When Eco mode is first enabled the correct charging rate of 6A is calculated since solar PV gen is approx 1kW, the lowest the EV can change at is 6A approx 1.4kW. However if charging is paused  then resumed Eco mode calculates a charging current of 9A (2.1kW) when solar PV still producing approx 1kW. Solar PV gen MQTT feed is correctly posting 1kW to EVSE.

Also if charging is paused (via web interface or button) then EV is unplugged then re-plugged Eco mode stays active when it should always revert to Normal (fast) charging mode when EV is unplugged to avoid accidentally having a slow charging rate for the next session 

![Screenshot 2019-05-12 at 15 40 50](https://user-images.githubusercontent.com/758844/57583030-3ac65800-74c4-11e9-96a7-8bd41c9b199a.png)
![Screenshot 2019-05-12 at 14 43 23](https://user-images.githubusercontent.com/758844/57583039-4dd92800-74c4-11e9-8462-827ae69495f6.png)

**Comment by jbakuwel** [comment]
For off grid systems it would actually be great if Eco mode (PV divert) would be persistent, ie. once set it remains set.
