### ISSUE TITLE
Wifi Scan results -> Invalid Json

### ISSUE THREAD

**Issue by adgoudsmit** [OpenEVSE/ESP8266_WiFi_v2.x#230]
When i tried to setup my AP to be used, i found out there was no wifi AP displayed on the website.
I eventually found out one of my neighbours has an AP with " in the name which caused the json to be invalid for the website to display the list of available accesspoints.

The UI was still just showing "Scanning..." so it did look like nothing was found.

Version used: 2.8.1

**Comment by glynhudson** [comment]
Thanks for reporting, that's very useful to know. Should be an easy fix

**Comment by jeremypoulter** [comment]
Well, that is just plain irritating, who has " in their SSID ;-) 

@glynhudson any objections to using [ArduinoJson ](https://arduinojson.org/) rather than handcrafting the JSON? Will automatically handle cases like this.

**Comment by glynhudson** [comment]
Haha agreed. It's bound to cause issues with other devices. Sure, that sounds like a good idea. 

At the same time it would be useful to implement some or all of:  https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/issues/204

**Comment by chris1howell** [comment]
Sounds like a great plan. Should clean things up a lot.

**Comment by fiveangle** [comment]
> Well, that is just plain irritating, who has " in their SSID ;-)

As SSIDEncoding field can be UNSPECIFIED (for arbitrary data) and UTF8, yes, even 32 NULL characters would be valid so using any string operations is a no-no

SSID: (╯°□°)╯︵ ┻━┻
