### ISSUE TITLE
Firmware update fails

### ISSUE THREAD

**Issue by chris1howell** [OpenEVSE/ESP8266_WiFi_v2.x#235]
Firmware update will fail if the update button is pressed twice requiring recovery with a serial device. 

Not all browsers display update progress or the status is not obvious.

Disabling the update button after a press would eliminate the problem. Additionally, a more visible conformation would be helpful.

**Comment by glynhudson** [comment]
Fix by https://github.com/OpenEVSE/openevse_wifi_gui/pull/16
