### ISSUE TITLE
Cant connect to emoncms 

### ISSUE THREAD

**Issue by samigroup** [OpenEVSE/ESP8266_WiFi_v2.x#240]
Can't seem to be able to establish a connection to the emoncms service. 
I followed the documentations for the node Id (0-9) and Key, to establish connection. do I need to update the Openssl SHA (server finger print) ?

**Comment by glynhudson** [comment]
Does it work when you remove the fingerprint? If you want a secure connection the fingerprint will need to be periodually updated. See this userguide for how to setup with emoncms.org https://guide.openenergymonitor.org/integrations/evse-setup
