### ISSUE TITLE
Solar PV Eco Divert Overrides kWh limit

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP8266_WiFi_v2.x#241]
If a user selects Eco mode to charge from solar PV and selects a kWh energy limit the EVSE will pause the charging once the energy limit has been reached but will then resume charging (ignoring the limit) when the next MQTT message is received from the solar PV divert. 

A possible fix for this could be to turn off Eco mode when an energy limit has been reached.

**Comment by jbakuwel** [comment]
Just a comment: for off grid users, turning off Eco mode is inconvenient. But I would imagine that off grid users would like to run something that controls OpenEVSE (like I do) and so re-enabling eco mode when the state changes is not difficult.

Another solution (if it exists) would imho be preferable.
