### ISSUE TITLE
ECO PV divert changes 'max current'

### ISSUE THREAD

**Issue by nitroushhh** [OpenEVSE/ESP8266_WiFi_v2.x#245]
When PV divert is selected the max current in the "setup" box gets set to the current value of 'charge rate' in the "charge mode' box when refresh is clicked in the browser.  This can also happen when clicking on the open evse tab in the browser.  This could be an issue with the UI javascript so this bug may be posted in the wrong area.

**Comment by jeremypoulter** [comment]
This is how it works, the solar divert sets the max current on the OpenEVSE and restores it after. Potentially we should hide this behaviour from the user but that will only work from the Web UI, The LCD menu will report the 'real' value.
