### ISSUE TITLE
Having UI open on more than 1 device causes issues.

### ISSUE THREAD

**Issue by nitroushhh** [OpenEVSE/ESP8266_WiFi_v2.x#246]
I don't know if this behaviour is known.  Having the EVSE UI open on a phone and tablet at the same time seems to cause conflicts as both instances seem to be able to tell the server what their version of the truth is.  So if i close my phone, then it has a record of the settings at that time.  I open the tablet and set eco pv on.  Going back to the phone seems to allow it to set the eco pv setting back to its old version of the truth.   Other parameters too.  So if i lose the eco pv setting then pausing doesn't resume when the sun comes out.  Also I can end up charging at much higher rate than my solar is generating without knowing that this change has occurred.

**Comment by jeremypoulter** [comment]
Yeah, the 'config' is only loaded when the UI is loaded. The 'status' is updated in real time for things like the current charging state are pushed live to all devices. Maybe we could add a config version number to the state that could be used to trigger a reload of the config.

**Comment by glynhudson** [comment]
Reloading the page to refresh the config is not a big issue. Important metrics like status are updated in real time between multiple devices
