### ISSUE TITLE
MDNS doesn't work w/ latest espressif platform (2.2.3)

### ISSUE THREAD

**Issue by lincomatic** [OpenEVSE/ESP8266_WiFi_v2.x#249]
I changed the platform in platformio.ini to 

platform = espressif8266@2.2.3

from the hardcoded v1.6.0, and

http://openevse.local 

stopped working.

I traced it to a missing line in the wifi_loop() function of wifi.cpp. You must add

MDNS.update();

into wifi_loop(), or it won't work. I'm actually puzzled why it was working with v1.6.0.

**Comment by jeremypoulter** [comment]
Looks like there is a completely new mDNS implementation that now needs the `MDNS.update()` call. Will add if/when we move to a later BSP version.

**Comment by glynhudson** [comment]
This is now fixed
