### ISSUE TITLE
Fitting it on ESP-01

### ISSUE THREAD

**Issue by martiinezz** [OpenEVSE/ESP8266_WiFi_v2.x#258]
Hi,

It looks like my ESP-01 with 512kb of flash is unable to handle this code.
I have disabled OTA in platform.io file but didn't help too much. 

I need just basic functionality without emoncms or Ohm. 
MQQT could stay but also go if necessary.

Any hints how to do it?

Ragards,
Martin

**Comment by glynhudson** [comment]
Sorry I'm afraid it's not possible to fit on an ESP-01

**Comment by martiinezz** [comment]
OK I resoldered ESP-01 with 4MB flash - everything works great :)
