### ISSUE TITLE
Feature request: smoothing documentation

### ISSUE THREAD

**Issue by jbakuwel** [OpenEVSE/ESP8266_WiFi_v2.x#270]
Hi,

Would it be possible to make the documentation about Divert smoothing attack and decay a bit more verbose, perhaps add an (i) icon to give a bit more explanation and maybe an example of how exactly this works.
While on topic, I've seen the Smoothed Current reach very interesting values (eg something like 2.342E-16). The Smoothed Current should perhaps not be updated while the unit is sleeping or not charging?

Jan

**Comment by glynhudson** [comment]
Hi Jan, 

Good idea, I've added some documentation here: https://github.com/OpenEVSE/ESP32_WiFi_V4.x#eco-mode-advanced-settings
