### ISSUE TITLE
Make RAPI comms asynchronous

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP8266_WiFi_v2.x#33]
Should help with #5 and should be based on the code in #20

**Comment by glynhudson** [comment]
Has this been implemented in #20? Can this issue be closed?

**Comment by jeremypoulter** [comment]
Not quite, the sendCmd call still blocks while waiting for a response. We need to change to a model where sendCmd takes a callback and that is called when the RAPI response is received. 

FYI, sendCmd will block for around 20mS in happy cases, and up to 500mS if something goes wrong. This is probably ok right now but may need resolving if more changes for #5 are needed.
