### ISSUE TITLE
Implement HTTPS certificates

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP8266_WiFi_v2.x#44]
The Git version of the ESP Arduino Core now supports certificate validation; https://github.com/esp8266/Arduino/pull/3271

**Comment by jeremypoulter** [comment]
Looks like this may be needed for ESP32 support, SHA-1 (quite reasonably) isn't supported.

**Comment by jeremypoulter** [comment]
Will be part of #219

**Comment by glynhudson** [comment]
now implemented in ESP32 versionhttps://github.com/OpenEVSE/ESP32_WiFi_V3.x/pull/97
