### ISSUE TITLE
Inconsistent use of GFCI/GFI

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP8266_WiFi_v2.x#60]
GFCI/GFI look to both be used interchangeably, should be consistent across the OpenEVSE/OpenEVSE WiFi (which probably means using GFI)

**Comment by chris1howell** [comment]
Okay, GFI is the better International used term.

**Comment by glynhudson** [comment]
Has this been fixed @jeremypoulter ? Can this issue be closed?
