### ISSUE TITLE
Implement Ammeter Calibration

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP8266_WiFi_v2.x#61]
Would probably help with setup to implement a version of the [Ammeter Calibrator](https://github.com/OpenEVSE/open_evse/tree/stable/ammeter_cal) in the web UI.

**Comment by glynhudson** [comment]
I don't think this is needed in the UI, or at least not a priority. It's a one-off task that could easily be done via RAPI web interface
