### ISSUE TITLE
Simple Status UI: elapsed time? 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP8266_WiFi_v2.x#66]
I've made a start at making a simple status UI box to sit at the top of the page. The idea is that this status UI should show the user at a glance the most important things. e.g is the car charging? At what rate? How many Kwh so far? 

One useful metric that we're not currently displaying is elapsed time. Elapsed time (in seconds) is returned in the 2nd element via RAPI get status `$GS`. @jeremypoulter do you think it would be possible to get elapsed time (in minutes) onto the UI display and add it to my status UI box as a third column? 

I think it would be also good if the status message e.g. "Charging / Waiting etc." was highlighted in the same color and the LCD. e.g. green = charging , purple = sleeping / waiting.

Any feedback on this proposed status UI box? Do you think it' useful? 

![screenshot 2017-08-07 at 01 15 26](https://user-images.githubusercontent.com/758844/29008410-5dad1ee6-7b0e-11e7-8749-b4e2059b33de.png)

**Comment by jeremypoulter** [comment]
How about;

![screenshot 2017-08-08 15 48 43](https://user-images.githubusercontent.com/6116992/29078156-876e414e-7c51-11e7-970c-60d410c95cc8.png)

![screenshot 2017-08-08 15 48 58](https://user-images.githubusercontent.com/6116992/29078159-897c2654-7c51-11e7-89d1-3a68214eb82e.png)

pushed those changes to the branch

**Comment by glynhudson** [comment]
That's great! Love it, exactly what I had in mind. 

Could the colour glow match the LCD background colours?

What do you think @chris1howell ?

**Comment by jeremypoulter** [comment]
> Could the colour glow match the LCD background colours?

It does (kind of), the actual LCD colours look terrible in the UI, in this example the blue is close to the background of the LCD in charging mode (as opposed to cyan of the LCD text). The shadow is the same colour as the left border but with an opacity applied so will naturally be darker as with the LCD, but that being said I have no objections to tweaking the colours.

**Comment by chris1howell** [comment]
Beautiful... Love it!

On Aug 8, 2017 8:49 AM, "Jeremy Poulter" <notifications@github.com<mailto:notifications@github.com>> wrote:

Could the colour glow match the LCD background colours?

It does (kind of), the actual LCD colours look terrible in the UI, in this example the blue is close to the background of the LCD in charging mode (as opposed to cyan of the LCD text). The shadow is the same colour as the left border but with an opacity applied so will naturally be darker as with the LCD, but that being said I have no objections to tweaking the colours.

**Comment by jeremypoulter** [comment]
FYI: not that these pictures really do the LCD justice.... 

![image](https://user-images.githubusercontent.com/6116992/29081302-1efbd5f0-7c5a-11e7-9674-db07a73e5894.png)
![2017-08-08 10 54 40](https://user-images.githubusercontent.com/6116992/29081121-96d3c57a-7c59-11e7-9b55-529c19ee61dc.jpg)

![image](https://user-images.githubusercontent.com/6116992/29081306-232de834-7c5a-11e7-9ff9-472cce3eb57d.png)
![2017-08-08 10 55 08](https://user-images.githubusercontent.com/6116992/29081124-96d8b152-7c59-11e7-81f5-aaf11a5af226.jpg)

![image](https://user-images.githubusercontent.com/6116992/29081312-267dd404-7c5a-11e7-90e1-211f58034b13.png)
![2017-08-08 10 55 01](https://user-images.githubusercontent.com/6116992/29081125-96dac226-7c59-11e7-8e3b-31e7c98a102a.jpg)

**Comment by glynhudson** [comment]
Awsome! Looks great. Nice work :+1:

**Comment by jeremypoulter** [comment]
Just for reference some notes from Hangout discussion with @glynhudson.

> @glynhudson: thanks alot, I'll give it a try this evening. Instead of having a status only page I was thinking of having an 'Advanced' section at the bottom of the page which would show a few elements that would be hidden by default 

![image](https://user-images.githubusercontent.com/6116992/29142133-d1d74bf2-7d48-11e7-9c7f-943e466ec958.png)

> @glynhudson: e.,g. the elements marked in red could be hidden by default then shown if a users taps an "advanced" button. Maybe this would be simpler than making more tabs? 

> @glynhudson: Would like to get to the stage where a user had everything they need for day-to-day use on a single tab. e.g. setting timers, charging status. 

> @jeremypoulter: Safety should probably not be hidden if any of the tests have failed or disabled

> @glynhudson: yes, if dev mode is not enabled 

> @jeremypoulter: I guess enabling dev mode should explicitly enable advanced mode

> @glynhudson: yes, why not

**Comment by jeremypoulter** [comment]
Implemented in #71
