### ISSUE TITLE
Session Wh counter does not reset if using delay timer?

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP8266_WiFi_v2.x#72]
In the past when charging with my OpenEVSE I've always used the onboard charging timer in my Nissan LEAF, however now I have the ability to easily set the OpenEVSE delay timer via the Wifi 2.0 GUI interface I have now turned off the car internal timer and am now using the OpenEVSE delay timer to schedule charging overnight. 

Once issue I've noticed is the OpenEVSE Wh session counter does not reset in between charging sessions when the delay timer is active. I.e previously when the car was unplugged then replugged in the OpenEVSE session wh counter would reset. 

@chris1howell  @lincomatic is this a known bug in 3.11.3? Or is it due to the Wifi 2.0 FW? Are you able to replicate? 

e.g. my session wh counter is now 35 Kwh which is impossible for a single session since my 24kWh Nissan LEAF only has 20 Kwh of usable capacity! Also I'm pretty sure my domestic single phase-supply would struggle to deliver 23kWh in 10min! Btw I'm loving the new UI, nice work @jeremypoulter 👍 

![screenshot 2017-08-10 at 00 51 05](https://user-images.githubusercontent.com/758844/29148551-19298c46-7d66-11e7-8d10-9d74c1888f34.png)

**Comment by glynhudson** [comment]
Known issue with OpenEVSE FW, confirmed by @chris1howell

**Comment by glynhudson** [comment]
Issue opened on open_evse FW repo: https://github.com/lincomatic/open_evse/issues/76

**Comment by glynhudson** [comment]
Fixed in open_evse FW 4.10.4. Thanks @lincomatic 👍

**Comment by glynhudson** [comment]
Hi @teslatradeup ,

You can download pre-compiled open_evse FW from here: https://github.com/openenergymonitor/open_evse/releases/

Please note that these are EU firmware releases, see these changes listed here: https://github.com/openenergymonitor/open_evse#changes-by-openenergymonitor

Be sure to download the OpenEVSE release not the EmonEVSE if you are using an OpenEVSE.

**Comment by teslatradeup** [comment]
Oh man, I'm in Canada so I guess this EU firmware wouldnt work for me right?

Do you know if there is a US repo that has been updated by any chance?

Thanks for your help!

**Comment by glynhudson** [comment]
I will work, the main changes are L2 by default and limit max charging
current to 32A. If you can live with these changes then it will work just
fine.

- sent from my mobile device

**Comment by teslatradeup** [comment]
Ok perfect - that's actually fine by me. Thanks a lot! :)

Martin Provost

**Comment by chris1howell** [comment]
Yes, we are testing a 5.0 release now. It should be uploaded in a couple days.

On Wed, Oct 3, 2018, 6:26 AM cmgj74 <notifications@github.com<mailto:notifications@github.com>> wrote:
I would be interested in a US updated version as well, since I can charge
at 40AMPS and wouldn't want to lose that. Any possibility of that/or
updating the version on Chris's side?
https://github.com/OpenEVSE/open_evse/releases

Thanks!

**Comment by cmgj74** [comment]
Awesome!  Thanks Chris!
