### ISSUE TITLE
Web page hanging, browser refresh required to fix 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP8266_WiFi_v2.x#75]
Often when trying to load the web page from the ESP the page hangs on "loading", after a browser refresh (sometimes two is required) the page loads. Here is a network activity capture showing the page hanging the subsequently loading after a page refresh:

![selection_094](https://user-images.githubusercontent.com/758844/29364894-ec2fda66-828c-11e7-94f9-841530957231.png)

![selection_095](https://user-images.githubusercontent.com/758844/29364895-ec3144aa-828c-11e7-9618-2c3e70dc73e9.png)

**Comment by roy13** [comment]
This feels similar to the issue i raised back in #41. I've been content to continue with original WiFi RAPI but i'm really keen to try MQTT. Anyway i've flashed a brand new Node MCU 12E using Arduino and i get stuck on the first image above until the WiFi AP seems to drop out. No amount of refreshing seems to assist.

**Comment by jeremypoulter** [comment]
Should be resolved after #87
