### ISSUE TITLE
'automatically' set current time setting misleading?

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP8266_WiFi_v2.x#76]
From this discussion https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/issues/15 I remember that the auto time should be obtained from the web browser. I remember when I initially tested this when #51 was merged it seemed to work. 

However testing again now it seems not to work, see attached. Tested in both firefox and Chrome

![selection_096](https://user-images.githubusercontent.com/758844/29365106-ae319780-828d-11e7-98e7-13864c672679.png)

**Comment by glynhudson** [comment]
Ah, I just realised I needed to hit the "Set" button! :+1:  

Having the 'Automatic" toggle is slightly misleading as I assumed that having automatic enabled would update the time automatically. Is this possible? To update the time each time the page is opened? Maybe an overkill? However this would automatically handle daylight saving time updates, since the web browser time would automatically update then the openevse would then autoupdate. 

I've renamed the "Set" button to "Update", since the openevse time is never not set, it's just incorrect until updated.

**Comment by jeremypoulter** [comment]
I don't think automatically updating the time whenever the browser is opened is necessarily a good idea. It was pointed out in #15 that the client browser may be in a different timezone for example.

Maybe we could just check and if the time is out by more than an hour open a pop up?

**Comment by glynhudson** [comment]
Very true, although I would argue that it would be very unlikely that the client browser would be a different timezone. A popup notification would be a good solution. It's important that the time is set correctly or else the delay timer won't work as expected!

**Comment by jeremypoulter** [comment]
I didn't think we had come to a conclusion on what to do with this issue. I did find another example (OpenWRT I think) that did the same thing. They had a button "Sync with Browser". We could change Automatic to Browser?

**Comment by glynhudson** [comment]
Yes, good idea. Renaming the button to "Sync with Browser" makes a lot of sense.
