### ISSUE TITLE
Print IP address to LCD on WiFi connect

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP8266_WiFi_v2.x#85]
After a hard reset I connected to the ESP WiFi AP and entered my SSID password. The Wifi ESP connected successfully. It would be very useful if at this point the ESP printed to the openEVSE LCD to announce successful connection (or otherwise!) it's new IP address on the network like it does at startup.

**Comment by jeremypoulter** [comment]
It should do this already, however I have already made some more
improvements to the flow/LCD display on my install_improvements branch.

**Comment by glynhudson** [comment]
Awesome! Thanks. I'm pretty sure it doesn't currently, I was videoing the
lcd at the time with thoughts to make a setup video

- sent from my mobile device

**Comment by jeremypoulter** [comment]
Fixed as part of #90
