### ISSUE TITLE
Upgrade path for ESP WiFi V1 users

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP8266_WiFi_v2.x#86]
There is a large users base of OpenEVSE users running @chris1howell WiFi EPS V1 FW:

https://github.com/OpenEVSE/ESP8266_WiFi_v1.x

It would be very useful if users could update from V1 > V2. 

- V1 has a working HTTP update
- It's acceptable IMO for the config to be lost, therefore the user would need to re-enter their WiFi password and Emoncms API key. Do you agree @chris1howell ?
- It's acceptable for the update to be a two-part process if required. Most OpenEVSE users should be happy following update instructions. 
- Having to resort to serial update should be avoided if possible

**Comment by jeremypoulter** [comment]
Needs testing but should be fixed after #87 and #90
