### ISSUE TITLE
Some checksums are printed in interface

### ISSUE THREAD

**Issue by fab33** [OpenEVSE/ESP8266_WiFi_v2.x#88]
like Level 2 Maximum:  80^29

fimrware D4.6.0
protocol 3.0.1
OpenEVSE 2.1.0

**Comment by jeremypoulter** [comment]
I think this will be restored on the master branch.

**Comment by fab33** [comment]
We can use master branch ? need FTDI flash or we can make OTA (spifss changes ?)

**Comment by jeremypoulter** [comment]
With the addition of #87 I think the master will be ok for use. SPIFFS is no longer used so OTA works fine.

**Comment by jeremypoulter** [comment]
I think this will be restored on the master branch.

**Comment by fab33** [comment]
Works fine with current master branch.
