### ISSUE TITLE
Investigate Edge compatibility 

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP8266_WiFi_v2.x#92]
Sean Fosberry has reported that the web page does not load on Microsoft Edge: 

https://community.openenergymonitor.org/t/openevse-with-wifi-build-v2-and-testing/4993/13?u=glyn.hudson

**Comment by jeremypoulter** [comment]
Fundamentally this is caused by me-no-dev/ESPAsyncWebServer#94 so will need to fix this to enable full support in Edge, however #99 fixes enough to make the UI usable in Edge/IE
