### ISSUE TITLE
Verify in Arduino

### ISSUE THREAD

**Issue by roy13** [OpenEVSE/ESP8266_WiFi_v2.x#94]
Thanks Glyn i saw the post on openenergymonitor but i have used my allowed 3 posts in one topic and have been cut off.
I assume the server_improvements is the github file to download eliminating memory problems. However when i compile on Arduino i get this.
two or more data types in declaration of 'event_send'
referring to line 174; void event_send(String event)

**Comment by glynhudson** [comment]
Hi @roy13 

I've now updated your user on our forum to remove the limitation. 

@jeremypoulter can confirm but I beleive after the latest updates the FW will no longer compile using Arduino IDE. You will need to use PlatformIO

**Comment by jeremypoulter** [comment]
@roy13, @glynhudson I was trying to keep Arduino IDE compatibility but I have not checked it recently. I will have a look and see if there is a quick fix.
